adverts/urls.py
from django.urls import path

from adverts.views import (
    AdvertListView, AdvertCategoryListView, AdvertCityListView, AdvertUserListView, AdvertDetailView,
    AdvertCreateTemplateView, AdvertCreateView, CommentCreateView, ExtraCommentsAJAXView
)

app_name = 'adverts'

urlpatterns = [
    path('', AdvertListView.as_view(), name='adverts-list'),
    path('<slug:category_slug_name>', AdvertCategoryListView.as_view(), name='category-list'),
    path('city/<slug:city_slug_name>', AdvertCityListView.as_view(), name='city-list'),
    path('user/<str:fio>', AdvertUserListView.as_view(), name='user-list'),
    path('<slug:category_slug_name>/<slug:advert_slug_title>/<int:id>', AdvertDetailView.as_view(), name='detail'),
    path('advert/add', AdvertCreateTemplateView.as_view(), name='advert-add'),
    path('advert/create', AdvertCreateView.as_view(), name='advert-create'),
    path('comment/create', CommentCreateView.as_view(), name='comment-create'),
    path('ajax/extra-comments', ExtraCommentsAJAXView.as_view(), name='get-extra-comments'),
]

blogs/urls.py
from django.urls import path

from blogs.views import BlogListView, BlogByTagListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('tag/<slug:tag_name>', BlogByTagListView.as_view(), name='by_tag'),
    path('<slug:blog_title>', BlogDetailView.as_view(), name='detail'),
    # path('<slug:blog_title>/<int:id>', BlogDetailView.as_view(), name='detail'),
]

templates/blocks/forms/_create_advert.html
 <div class="card mb-3">
    <div class="card-body mt-3 mb-3">
        <h1>Добавление объявления</h1>
        <h3>Подайте объявление для публикации на портале:</h3>
        <ul class="list-unstyled">
            <li>&mdash;&nbsp;Заполните форму ниже на данной странице</li>
            <li>&mdash;&nbsp;Не забудьте выбрать категорию, в которой будет размещаться Ваше объявление, озаглавьте и введите текст объявления, укажите контактную информацию для связи с посетителями портала, отправить на модерацию</li>
        </ul>
        <div class="card text-dark bg-light mt-3">
            <div class="card-body mt-3 mb-3">
                <h5 class="card-title">
                    <i class="fas fa-exclamation-circle"></i>
                    Внимание!
                </h5>
                <p class="card-text">Ваше объявление перед публикацией на портале пройдет модерацию.</p>
                <p class="card-text">Идентичные объявления и объявления с контактной информацией в поле <mark>"Текст Вашего объявления"</mark> будут удалены.</p>
            </div>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <form action="{% url 'adverts:advert-create' %}" method="post" class="mt-3">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.name == 'text' %}
                        <div class="progress">
                            <div class="progress-bar char-counter-bar"
                                 role="progressbar"
                                 aria-valuenow="0"
                                 aria-valuemin="0"
                                 aria-valuemax="100"></div>
                        </div>
                        <span class="char-counter float-right mt-1"></span>
                    {% endif %}
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="btn {{ cs.form.btn.color }}">Отправить на модерацию</button>
        </form>
    </div>
</div>

templates/blocks/forms/checkbox.html
{% load static %}

<div class="{{ class }}">
    <label>
        {{ field }} {{ label }}
    </label>
</div>

templates/blocks/forms/fields_errors.html
{% load static %}

{% if form.errors %}
    <div class="fields-errors">
        {% for field in form.visible_fields %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ error|escape }}
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

templates/blocks/forms/floating_label_field.html
{% load static %}

<div class="form-label-group">
    {{ field }}
    <label for="{{ field.field.widget.attrs.id }}">{{ label }}</label>
</div>
<div class="invalid-feedback">
   {% if field.errors %}
        {% for error in field.errors %}
            {{ error|escape }}
        {% endfor %}
    {% endif %}
</div>

templates/blocks/forms/non_field_errors.html
{% load static %}

{% if form.non_field_errors %}
    <div class="non-field-errors">
        {% for error in form.non_field_errors %}
            {{ error|escape }}
        {% endfor %}
    </div>
{% endif %}