adverts/urls.py
from django.urls import path

from adverts.views import (
    AdvertListView, AdvertCategoryListView, AdvertCityListView, AdvertUserListView, AdvertDetailView,
    AdvertCreateTemplateView, AdvertCreateView, CommentCreateView, ExtraCommentsAJAXView
)

app_name = 'adverts'

urlpatterns = [
    path('', AdvertListView.as_view(), name='adverts-list'),
    path('<slug:category_slug_name>', AdvertCategoryListView.as_view(), name='category-list'),
    path('city/<slug:city_slug_name>', AdvertCityListView.as_view(), name='city-list'),
    path('user/<str:fio>', AdvertUserListView.as_view(), name='user-list'),
    path('<slug:category_slug_name>/<slug:advert_slug_title>/<int:id>', AdvertDetailView.as_view(), name='detail'),
    path('advert/add', AdvertCreateTemplateView.as_view(), name='advert-add'),
    path('advert/create', AdvertCreateView.as_view(), name='advert-create'),
    path('comment/create', CommentCreateView.as_view(), name='comment-create'),
    path('ajax/extra-comments', ExtraCommentsAJAXView.as_view(), name='get-extra-comments'),
]

blogs/urls.py
from django.urls import path

from blogs.views import BlogListView, BlogByTagListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('tag/<slug:tag_name>', BlogByTagListView.as_view(), name='by_tag'),
    path('<slug:blog_title>', BlogDetailView.as_view(), name='detail'),
    # path('<slug:blog_title>/<int:id>', BlogDetailView.as_view(), name='detail'),
]

users/urls.py
from django.urls import path

from users.views import (
    UserLoginView, UserLogoutView, UserProfileAdvertListView, UserProfileCityListView, UserProfileCategoryListView,
    UserProfileFioListView, UserRegistrationFormView, AccountActivationDoneTemplateView, AccountActivationConfirmView
)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('registration/', UserRegistrationFormView.as_view(), name='registration'),
    path('<int:user_id>/', UserProfileAdvertListView.as_view(), name='profile'),
    path('activate/done/', AccountActivationDoneTemplateView.as_view(), name='activate-done'),
    path('activate/confirm/<str:uidb64>/<str:token>/', AccountActivationConfirmView.as_view(), name='activation-confirm'),
    path('profile/city/<slug:city_slug_name>/', UserProfileCityListView, name='city-list'),
    path('profile/category/<slug:category_slug_name>/', UserProfileCategoryListView.as_view(), name='category-list'),
    path('profile/user/<str:fio>/', UserProfileFioListView.as_view(), name='user-list'),
]

templates/blocks/_title.html
{% load thumbnail %}
<title>{{ page_meta.title }}</title>
<meta name="description" content="{{ page_meta.description }}">
{% if page_meta.keywords %}
    <meta name="keywords" content="{% for k in page_meta.keywords %}{{ k }}{% if not forloop.last %}, {% endif %}{% endfor %}">
{% endif %}
<meta property="og:title" content="{{ page_meta.title }}">
<meta property="og:description" content="{{ page_meta.description }}">
<meta property="og:type" content="{{ page_meta.type }}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
{% if page_meta.img %}
    <meta property="og:image" content="{% thumbnail page_meta.img "x350" as i %}{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}{{ i.url }}{% endthumbnail %}">
{% endif %}
<meta property="og:site_name" content="{{ request.get_host }}">

templates/blocks/footer.html
<footer class="footer {{ cs.footer.background_color }} text-body">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <ul class="list-unstyled">
                    <li><h5>Разделы</h5></li>
                    <li>
                        <a href="{% url 'adverts:adverts-list' %}" class="{{ cs.footer.link_color }}">
                            Объявления
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'blogs:list' %}" class="{{ cs.footer.link_color }}">Статьи</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3">
                <ul class="list-unstyled">
                    <li><h5>Категории</h5></li>
                    {% for c in categories %}
                        <li>
                            <a href="{% url "adverts:category-list" c.slug_name %}" class="{{ cs.footer.link_color }}">{{ c.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-3"></div>
        </div>
    </div>
</footer>

templates/blocks/navbar.html
<nav class="navbar navbar-expand-lg {{ cs.navbar.color }} {{ cs.navbar.background_color }} mb-4">
    <a class="navbar-brand" href="{% url 'adverts:adverts-list' %}">{{ site_name }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            {% with request.resolver_match.view_name as vn %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if vn == 'users:profile' or vn == 'users:city-list' or vn == 'users:category-list' or vn == 'users:user-list' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'users:profile' request.user.pk %}">Личный кабинет</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Личный кабинет</a>
                    </li>
                {% endif %}
                <li class="nav-item {% if vn == 'adverts:adverts-list' or vn == 'adverts:category-list' or vn == 'adverts:city-list' or vn == 'adverts:user-list' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'adverts:adverts-list' %}">
                        Объявления <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item {% if vn == 'blogs:list' or vn == 'blogs:by_tag' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'blogs:list' %}">Статьи</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
                    </li>
                {% endif %}
            {% endwith %}
        </ul>
        <form class="form-inline">
            <a href="{% url 'adverts:advert-add' %}" class="btn {{ cs.navbar.btn.color }}">
                <i class="fas fa-pencil-alt"></i>
                Подать объявление
            </a>
        </form>
    </div>
</nav>

templates/blocks/paginator.html
{% if is_paginated %}
    <nav aria-label="Page navigation" class="mb-4">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for r in page_obj.page_range %}
                {% if r == page_obj.number %}
                    <li class="page-item active">
                        <a href="#" class="page-link">{{ r }}</a>
                    </li>
                {% elif not r %}
                    <li class="page-item">
                        <a href="#" class="page-link">...</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ r }}">{{ r }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/blocks/sidebar_left.html
{% if request.resolver_match.app_name == 'users' %}
    {% include "blocks/sidebar/_comments_for_user_advs.html" %}
{% else %}
    {% include "blocks/sidebar/_comments.html" %}
{% endif %}

templates/blocks/sidebar_right.html
{% include "blocks/sidebar/_categories.html" with categories=categories cs=color_scheme only %}
{% include "blocks/sidebar/_media_adsense.html" with site_name=site_name only %}